version: "3.9"

services:
  postgres_data:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - 5432:5432
  redis_data:
    image: redis:latest
    ports:
      - 6379:6379